/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/RoboticHorse/scene.gltf --transform 
Files: public/models/RoboticHorse/scene.gltf [8.74KB] > C:\Users\Admin\Documents\programación\3d-portfolio\scene-transformed.glb [93.71KB] (-972%)
Author: DevPoly3D (https://sketchfab.com/DevPoly3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/futuristic-robotic-horse-sci-fi-mech-animal-193f39c0ee104e6099fbf6a4f548c426
Title: Futuristic Robotic Horse | Sci-Fi Mech Animal
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube003_Red_shiny_tiles_0.geometry} material={materials.Red_shiny_tiles} position={[0, 0.709, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.327, 0.477, 0.477]} />
      <mesh geometry={nodes.Cube003_Touched_Plastic_Rough_0.geometry} material={materials.Touched_Plastic_Rough} position={[0, 0.709, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.327, 0.477, 0.477]} />
      <mesh geometry={nodes.Cube003_Material001_0.geometry} material={materials['Material.001']} position={[0, 0.709, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.327, 0.477, 0.477]} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
