/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Compass2.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { Float, useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

const Compass = (props) => {
  const { scene } = useGLTF('/models/Compass/Compass2.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <Float floatIntensity={1}   >
      <group {...props} dispose={null} scale={7}>
        <primitive object={nodes._rootJoint} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['compass.002']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['glass.002']} />
      </group>
    </Float>

  )
}

useGLTF.preload('/models/Compass/Compass2.glb')

export default Compass