/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 napoleonPig2.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { Float } from '@react-three/drei'

const Pig = (props) => {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/Pig/napoleonPig2.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <Float> 
      <group ref={group} {...props} dispose={null}>
      <group name="Scene" scale={0.4}>
        <group name="Esqueleto" position={[0, -3.091, 2.534]}>
          <primitive object={nodes.Centro} />
          <primitive object={nodes.Rpierna} />
          <primitive object={nodes.Rantebrazo} />
          <primitive object={nodes.Lpierna} />
          <primitive object={nodes.Lantebrazo} />
          <skinnedMesh name="Esfera" geometry={nodes.Esfera.geometry} material={materials['Material.002']} skeleton={nodes.Esfera.skeleton} />
          <skinnedMesh name="Esfera011" geometry={nodes.Esfera011.geometry} material={materials['Material.003']} skeleton={nodes.Esfera011.skeleton} />
          <skinnedMesh name="Esfera012" geometry={nodes.Esfera012.geometry} material={materials['Material.003']} skeleton={nodes.Esfera012.skeleton} />
        </group>
      </group>
    </group>
    </Float>
    
  )
}

useGLTF.preload('/models/Pig/napoleonPig2.glb')

export default Pig