/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 zennetz2_90s_notebook.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/zennetz2_90s_notebook.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.001, 0.088, -0.173]} rotation={[Math.PI / 2, 0, 0]} scale={0.05}>
        <mesh geometry={nodes.Object_8.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_9.geometry} material={nodes.Object_9.material} />
      </group>
      <mesh geometry={nodes.Object_11.geometry} material={materials['Material.012']} />
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.002']} position={[-0.003, 0.004, -0.192]} rotation={[Math.PI / 2, 0, 0]} scale={0.05} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.002']} position={[0.004, 0.002, -0.001]} rotation={[Math.PI / 2, 0, 0]} scale={0.05} />
    </group>
  )
}

useGLTF.preload('/zennetz2_90s_notebook.glb')
